" 关闭兼容
set nocompatible 

" 取消备份文件生成
set nobackup
set nowritebackup
set noswapfile
set mouse=a

" 可以使用正常的删除
set bs=2

" 换屏按键
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" 显示光标当前位置
set ruler
" 行号显示
set number
" 行宽80
set textwidth=80
" 不换行
set nowrap

" 搜索功能
set hlsearch
set incsearch

set wildmenu "智能补全

" 标志线
set cursorline
set cursorcolumn

" 缩进
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab



set autochdir
set showcmd

filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'vim-scripts/vim-autopep8'
Plugin 'altercation/vim-colors-solarized'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/nerdtree'
Plugin 'Lokaltog/vim-powerline'
Plugin 'davidhalter/jedi-vim'
Plugin 'nathanaelkane/vim-indent-guides'
call vundle#end()

" 高亮语法
filetype plugin indent on
syntax on 

" vim-powerline
set laststatus=2
" jedi-vim
let g:jedi#usages_command = "<leader>z"
let g:jedi#popup_on_dot = 0
let g:jedi#popup_select_first = 0

let NERDSpaceDelims = 1
let NERDTreeHighlightCursorline=1
let NERDTreeIgnore=[ '.pyc$', '.pyo$', '.obj$', '.o$', '.so$', '.egg$', '^.git$', '^.svn$', '^.hg$' ]
let g:autopep8_disable_show_diff=1
let g:solarized_termtrans=2
let g:solarized_contrast='normal'
let g:solarized_visibility='normal'
set background=dark
colorscheme solarized
